export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const USER_MODEL = 'USER_MODEL';
export const ROLE_MODEL = 'ROLE_MODEL';
export const PRODUCT_MODEL = 'PRODUCT_MODEL';
export const PRODUCT_DETAIL_MODEL = 'PRODUCT_DETAIL_MODEL';
